### PR TITLE
Packaging, CI, renaming to whole_body_state_rviz_plugin

### PR DESCRIPTION
**Pull request by wxmerkt**
Complements https://github.com/cmastalli/state_msgs/pull/3

It's likely this won't build on Noetic but we can fix that / cross that bridge when we get to it.

### CODE REVIEW

**Review by cmastalli — APPROVED** [review]
Everything looks good. Thank you so much.

I will directly update the README

**Comment by wxmerkt** [comment]
Thanks :-) I think Travis may have to be manually enabled to run on both repositories. You can go to https://travis-ci.org/account/repositories, reload the list of repositories and toggle it to on/enabled. There's also a description on how to do this [here](https://docs.travis-ci.com/user/tutorial/).

**Comment by cmastalli** [comment]
> Thanks :-) I think Travis may have to be manually enabled to run on both repositories. You can go to https://travis-ci.org/account/repositories, reload the list of repositories and toggle it to on/enabled. There's also a description on how to do this [here](https://docs.travis-ci.com/user/tutorial/).

I have enable them as you can see in the picture, is there something else to be done?
Screenshot from 2020-08-24 10-54-41

**Comment by wxmerkt** [comment]
No, that should be it. It will be activated/triggered during the next commit/push

**Pull request merged**
